
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ
  :"raid" => {
    #Какой vm box будем использовать
    :box_name => "alse-gui-base/1.7.6",
    :box_url => "https://dl.astralinux.ru/vagrant/alse-gui-base%2F1.7.6",
    #Указываем количество ядер ВМ
    :cpus => 2,
    #Указываем количество ОЗУ в мегабайтах
    :memory => 2048,
    :disks => {
            :sata1 => {
                :dfile => './sata1.vdi',
                :size => 250, # Megabytes
                :port => 1
            },
            :sata2 => {
                :dfile => './sata2.vdi',
                :size => 250,
                :port => 2
            },
            :sata3 => {
                :dfile => './sata3.vdi',
                :size => 250,
                :port => 3
            },
            :sata4 => {
                :dfile => './sata4.vdi',
                :size => 250,
                :port => 4
            },
            :sata5 => {
                :dfile => './sata5.vdi',
                :size => 250,
                :port => 5
            }
        }
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_url = boxconfig[:box_url]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            v.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
          end
          v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 6, '--device', 0, '--type', 'dvddrive', '--medium', '/usr/share/virtualbox/VBoxGuestAdditions.iso']
        end
      end
      config.vm.provision "shell", path: "../vboxprep.sh"
      config.vm.provision "shell", inline: <<-SHELL
        apt-get install -y mdadm smartmontools hdparm gdisk
        sleep 5
        echo "Выполняем перезагрузку"
      SHELL
        config.vm.provision 'shell', reboot: true
    end
  end
end
